"""
Export route — copies fully-annotated images and their YOLO .txt label files
to a chosen server-side output directory, together with classes.txt and data.yaml.

A media item is considered "completely annotated" when:
  - it has at least one annotation, AND
  - every annotation has status = 'accepted'  (no drafts or rejected ones)
"""

import shutil
from pathlib import Path
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.core.geometry import point_in_polygon
from app.core.utils import extract_video_name
from app.db import models
from app.db.session import get_db
from app.domain.schemas import AnnotationStatus, MediaType

router = APIRouter()

# ── Class definitions (must match frontend src/data/sample.ts exactly) ──────
EXPORT_CLASSES: list[tuple[int, str]] = [
    (0, "number_plate"),
    (1, "bike"),
    (2, "car"),
    (3, "bus_microbus"),
    (4, "large_vehicle"),
    (10, "Boundary"),
]

CLASSES_TXT = "\n".join(f"{cid} {name}" for cid, name in EXPORT_CLASSES) + "\n"

DATA_YAML_TEMPLATE = """\
# YOLO dataset descriptor – auto-generated by ITIS
path: {output_dir}
train: images
val: images

nc: {nc}
names:
{names_block}
"""


# ── Pydantic schemas ─────────────────────────────────────────────────────────

class ExportRequest(BaseModel):
    output_dir: str
    overwrite: bool = False


class ExportPreviewRead(BaseModel):
    qualified: int
    output_dir: str


class ExportResultRead(BaseModel):
    exported: int
    skipped: int
    output_dir: str


# ── Helpers ──────────────────────────────────────────────────────────────────

def _ensure_dataset(db: Session, dataset_id: UUID) -> models.Dataset:
    dataset = db.get(models.Dataset, dataset_id)
    if dataset is None:
        raise HTTPException(status_code=404, detail="Dataset not found")
    return dataset


def _qualified_media(db: Session, dataset_id: UUID) -> list[models.MediaItem]:
    """
    Return image MediaItems that have ≥1 annotation and all accepted.
    Uses a subquery approach: media where total annotation count equals
    accepted annotation count (and total > 0).
    """
    total_sub = (
        select(
            models.Annotation.media_id,
            func.count(models.Annotation.id).label("total"),
        )
        .group_by(models.Annotation.media_id)
        .subquery()
    )
    accepted_sub = (
        select(
            models.Annotation.media_id,
            func.count(models.Annotation.id).label("accepted"),
        )
        .where(models.Annotation.status == AnnotationStatus.ACCEPTED)
        .group_by(models.Annotation.media_id)
        .subquery()
    )

    items = db.scalars(
        select(models.MediaItem)
        .join(total_sub, models.MediaItem.id == total_sub.c.media_id)
        .join(accepted_sub, models.MediaItem.id == accepted_sub.c.media_id)
        .where(
            models.MediaItem.dataset_id == dataset_id,
            models.MediaItem.media_type == MediaType.IMAGE.value,
            total_sub.c.total > 0,
            accepted_sub.c.accepted == total_sub.c.total,
        )
        .order_by(models.MediaItem.created_at.asc())
    ).all()
    return list(items)


def _path_for_media(item: models.MediaItem) -> Path:
    """Resolve the physical file path for a media item (mirrors media.py logic)."""
    storage_key_path = Path(item.storage_key)
    from app.core.config import settings
    storage_path = (
        storage_key_path
        if storage_key_path.is_absolute()
        else settings.storage_root / storage_key_path
    )
    if storage_path.exists():
        return storage_path
    if item.source_path:
        source_path = Path(item.source_path)
        if source_path.exists():
            return source_path
    return storage_path


def _build_data_yaml(output_dir: str) -> str:
    nc = len(EXPORT_CLASSES)
    names_block = "\n".join(
        f"  {cid}: {name}" for cid, name in EXPORT_CLASSES
    )
    return DATA_YAML_TEMPLATE.format(
        output_dir=output_dir,
        nc=nc,
        names_block=names_block,
    )


def _write_label_file(label_path: Path, annotations: list[models.Annotation]) -> None:
    lines: list[str] = []
    
    boundary = next((a for a in annotations if a.class_id == 10), None)
    roi_polygon = boundary.polygon if boundary and boundary.polygon else None
    
    def is_inside_boundary(x: float, y: float) -> bool:
        if not boundary:
            return True
        if roi_polygon:
            return point_in_polygon(x, y, roi_polygon)
        left = boundary.x_center - boundary.width / 2
        right = boundary.x_center + boundary.width / 2
        top = boundary.y_center - boundary.height / 2
        bottom = boundary.y_center + boundary.height / 2
        return left <= x <= right and top <= y <= bottom

    for ann in annotations:
        if ann.class_id != 10 and not is_inside_boundary(ann.x_center, ann.y_center):
            continue
        lines.append(
            f"{ann.class_id} "
            f"{ann.x_center:.6f} "
            f"{ann.y_center:.6f} "
            f"{ann.width:.6f} "
            f"{ann.height:.6f}"
        )
    label_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Endpoints ────────────────────────────────────────────────────────────────

@router.get("/{dataset_id}/annotated/preview", response_model=ExportPreviewRead)
def preview_export(
    dataset_id: UUID,
    output_dir: str = "",
    db: Session = Depends(get_db),
) -> ExportPreviewRead:
    _ensure_dataset(db, dataset_id)
    items = _qualified_media(db, dataset_id)
    return ExportPreviewRead(qualified=len(items), output_dir=output_dir)


@router.post("/{dataset_id}/annotated", response_model=ExportResultRead)
def export_annotated(
    dataset_id: UUID,
    payload: ExportRequest,
    db: Session = Depends(get_db),
) -> ExportResultRead:
    _ensure_dataset(db, dataset_id)

    output_path = Path(payload.output_dir).expanduser()
    if not output_path.is_absolute():
        raise HTTPException(
            status_code=400,
            detail="output_dir must be an absolute path on the server",
        )

    images_dir = output_path / "images"
    labels_dir = output_path / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    items = _qualified_media(db, dataset_id)
    exported = 0
    skipped = 0

    exported = 0
    skipped = 0

    for item in items:
        dest_image = images_dir / item.file_name
        dest_label = labels_dir / (Path(item.file_name).stem + ".txt")

        if not payload.overwrite and dest_image.exists():
            skipped += 1
            continue

        src_path = _path_for_media(item)
        if not src_path.exists() or not src_path.is_file():
            skipped += 1
            continue

        # Copy image
        try:
            shutil.copy2(str(src_path), str(dest_image))
        except OSError:
            skipped += 1
            continue

        # Write label file
        annotations = db.scalars(
            select(models.Annotation)
            .where(models.Annotation.media_id == item.id)
            .order_by(models.Annotation.created_at.asc())
        ).all()
        _write_label_file(dest_label, list(annotations))
        exported += 1

    # Write metadata files
    (output_path / "classes.txt").write_text(CLASSES_TXT, encoding="utf-8")
    (output_path / "data.yaml").write_text(
        _build_data_yaml(str(output_path)), encoding="utf-8"
    )

    return ExportResultRead(
        exported=exported,
        skipped=skipped,
        output_dir=str(output_path),
    )
